"""add_joining_date_to_employee

Revision ID: 3deaf8daa66a
Revises: f73037edda09
Create Date: 2026-06-13 11:27:49.823735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3deaf8daa66a"
down_revision: Union[str, Sequence[str], None] = "f73037edda09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employees", sa.Column("joining_date", sa.Date(), nullable=True))
    op.execute("""
        UPDATE employees
        SET joining_date = DATE(created_at)
    """)

    op.alter_column("employees", "joining_date", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "joining_date")
    # ### end Alembic commands ###
