"""add_role_to_employee_table

Revision ID: ba3b3a156989
Revises: 97f91170405d
Create Date: 2026-06-01 14:13:11.379040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3b3a156989'
down_revision: Union[str, Sequence[str], None] = '97f91170405d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ROLE_ENUM = sa.Enum("UI","UX","Developer","HR",name="employeerole")

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _ROLE_ENUM.create(op.get_bind(), checkfirst=True)
    op.add_column('employees', sa.Column('role',_ROLE_ENUM , server_default='Developer', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'role')
    # ### end Alembic commands ###
