"""add_status_to_employee_table

Revision ID: ec016da5e57f
Revises: ba3b3a156989
Create Date: 2026-06-10 16:12:05.396634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec016da5e57f"
down_revision: Union[str, Sequence[str], None] = "ba3b3a156989"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_STATUS_ENUM = sa.Enum("Probation", "Active", "Inactive", name="employeestatus")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _STATUS_ENUM.create(op.get_bind(), checkfirst=True)
    op.add_column("employees", sa.Column("status", _STATUS_ENUM, server_default="Probation", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "status")
    # ### end Alembic commands ###
