"""add_experience_to_employee_table

Revision ID: f73037edda09
Revises: ec016da5e57f
Create Date: 2026-06-11 09:26:35.119971

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f73037edda09"
down_revision: Union[str, Sequence[str], None] = "ec016da5e57f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.add_column("employees", sa.Column("experience", sa.Integer(), nullable=True))
    op.execute("UPDATE employees SET experience = 1 WHERE experience IS NULL")
    op.alter_column("employees", "experience", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "experience")
    # ### end Alembic commands ###
